rootProject.name = 'QuickJSExample'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
include ':react-native-native-quickjs'
project(':react-native-native-quickjs').projectDir = new File(rootProject.projectDir, '../../android')
includeBuild('../node_modules/@react-native/gradle-plugin')
